2023-12-14 14:01:14,255:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-14 14:01:14,255:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-14 14:01:14,255:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-14 14:01:14,255:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-14 14:13:01,960:INFO:PyCaret ClassificationExperiment
2023-12-14 14:13:01,979:INFO:Logging name: clf-default-name
2023-12-14 14:13:01,986:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-12-14 14:13:01,987:INFO:version 3.2.0
2023-12-14 14:13:01,987:INFO:Initializing setup()
2023-12-14 14:13:01,987:INFO:self.USI: 18bb
2023-12-14 14:13:01,987:INFO:self._variable_keys: {'target_param', 'exp_id', 'data', 'exp_name_log', 'fold_shuffle_param', 'X', 'y_test', 'fix_imbalance', 'pipeline', 'gpu_param', 'gpu_n_jobs_param', 'is_multiclass', 'y_train', 'X_train', 'y', 'log_plots_param', 'seed', 'n_jobs_param', 'logging_param', 'idx', '_ml_usecase', 'USI', 'fold_groups_param', 'X_test', '_available_plots', 'fold_generator', 'html_param', 'memory'}
2023-12-14 14:13:01,987:INFO:Checking environment
2023-12-14 14:13:01,987:INFO:python_version: 3.11.6
2023-12-14 14:13:01,987:INFO:python_build: ('tags/v3.11.6:8b6ee5b', 'Oct  2 2023 14:57:12')
2023-12-14 14:13:01,988:INFO:machine: AMD64
2023-12-14 14:13:01,988:INFO:platform: Windows-10-10.0.22621-SP0
2023-12-14 14:13:01,994:INFO:Memory: svmem(total=8466100224, available=461721600, percent=94.5, used=8004378624, free=461721600)
2023-12-14 14:13:01,995:INFO:Physical Core: 2
2023-12-14 14:13:01,995:INFO:Logical Core: 4
2023-12-14 14:13:01,995:INFO:Checking libraries
2023-12-14 14:13:01,995:INFO:System:
2023-12-14 14:13:01,995:INFO:    python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
2023-12-14 14:13:01,995:INFO:executable: C:\Users\talla\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
2023-12-14 14:13:01,995:INFO:   machine: Windows-10-10.0.22621-SP0
2023-12-14 14:13:01,996:INFO:PyCaret required dependencies:
2023-12-14 14:13:02,421:INFO:                 pip: 23.2.1
2023-12-14 14:13:02,421:INFO:          setuptools: 65.5.0
2023-12-14 14:13:02,421:INFO:             pycaret: 3.2.0
2023-12-14 14:13:02,421:INFO:             IPython: 8.13.2
2023-12-14 14:13:02,421:INFO:          ipywidgets: 8.1.1
2023-12-14 14:13:02,421:INFO:                tqdm: 4.66.1
2023-12-14 14:13:02,421:INFO:               numpy: 1.25.2
2023-12-14 14:13:02,421:INFO:              pandas: 1.5.3
2023-12-14 14:13:02,421:INFO:              jinja2: 3.1.2
2023-12-14 14:13:02,421:INFO:               scipy: 1.10.1
2023-12-14 14:13:02,421:INFO:              joblib: 1.3.2
2023-12-14 14:13:02,421:INFO:             sklearn: 1.2.2
2023-12-14 14:13:02,421:INFO:                pyod: 1.1.2
2023-12-14 14:13:02,421:INFO:            imblearn: 0.11.0
2023-12-14 14:13:02,421:INFO:   category_encoders: 2.6.3
2023-12-14 14:13:02,421:INFO:            lightgbm: 4.1.0
2023-12-14 14:13:02,421:INFO:               numba: 0.58.1
2023-12-14 14:13:02,421:INFO:            requests: 2.31.0
2023-12-14 14:13:02,421:INFO:          matplotlib: 3.6.0
2023-12-14 14:13:02,421:INFO:          scikitplot: 0.3.7
2023-12-14 14:13:02,421:INFO:         yellowbrick: 1.5
2023-12-14 14:13:02,421:INFO:              plotly: 5.18.0
2023-12-14 14:13:02,421:INFO:    plotly-resampler: Not installed
2023-12-14 14:13:02,421:INFO:             kaleido: 0.2.1
2023-12-14 14:13:02,421:INFO:           schemdraw: 0.15
2023-12-14 14:13:02,421:INFO:         statsmodels: 0.14.0
2023-12-14 14:13:02,421:INFO:              sktime: 0.21.1
2023-12-14 14:13:02,437:INFO:               tbats: 1.1.3
2023-12-14 14:13:02,437:INFO:            pmdarima: 2.0.4
2023-12-14 14:13:02,437:INFO:              psutil: 5.9.5
2023-12-14 14:13:02,437:INFO:          markupsafe: 2.1.3
2023-12-14 14:13:02,438:INFO:             pickle5: Not installed
2023-12-14 14:13:02,438:INFO:         cloudpickle: 2.2.1
2023-12-14 14:13:02,438:INFO:         deprecation: 2.1.0
2023-12-14 14:13:02,439:INFO:              xxhash: 3.4.1
2023-12-14 14:13:02,439:INFO:           wurlitzer: Not installed
2023-12-14 14:13:02,439:INFO:PyCaret optional dependencies:
2023-12-14 14:13:02,473:INFO:                shap: Not installed
2023-12-14 14:13:02,473:INFO:           interpret: Not installed
2023-12-14 14:13:02,473:INFO:                umap: Not installed
2023-12-14 14:13:02,473:INFO:     ydata_profiling: Not installed
2023-12-14 14:13:02,473:INFO:  explainerdashboard: Not installed
2023-12-14 14:13:02,473:INFO:             autoviz: Not installed
2023-12-14 14:13:02,473:INFO:           fairlearn: Not installed
2023-12-14 14:13:02,473:INFO:          deepchecks: Not installed
2023-12-14 14:13:02,473:INFO:             xgboost: Not installed
2023-12-14 14:13:02,473:INFO:            catboost: Not installed
2023-12-14 14:13:02,473:INFO:              kmodes: Not installed
2023-12-14 14:13:02,473:INFO:             mlxtend: Not installed
2023-12-14 14:13:02,473:INFO:       statsforecast: Not installed
2023-12-14 14:13:02,473:INFO:        tune_sklearn: Not installed
2023-12-14 14:13:02,473:INFO:                 ray: Not installed
2023-12-14 14:13:02,473:INFO:            hyperopt: 0.2.7
2023-12-14 14:13:02,473:INFO:              optuna: 3.5.0
2023-12-14 14:13:02,473:INFO:               skopt: 0.9.0
2023-12-14 14:13:02,473:INFO:              mlflow: 2.8.1
2023-12-14 14:13:02,473:INFO:              gradio: Not installed
2023-12-14 14:13:02,473:INFO:             fastapi: Not installed
2023-12-14 14:13:02,473:INFO:             uvicorn: Not installed
2023-12-14 14:13:02,473:INFO:              m2cgen: Not installed
2023-12-14 14:13:02,473:INFO:           evidently: Not installed
2023-12-14 14:13:02,473:INFO:               fugue: Not installed
2023-12-14 14:13:02,473:INFO:           streamlit: 1.28.2
2023-12-14 14:13:02,473:INFO:             prophet: Not installed
2023-12-14 14:13:02,473:INFO:None
2023-12-14 14:13:02,473:INFO:Set up data.
2023-12-14 14:13:02,488:INFO:Set up folding strategy.
2023-12-14 14:13:02,488:INFO:Set up train/test split.
2023-12-14 14:13:02,524:INFO:Set up index.
2023-12-14 14:13:02,524:INFO:Assigning column types.
2023-12-14 14:13:02,540:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-12-14 14:13:02,624:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-14 14:13:02,637:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-14 14:13:02,780:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:02,781:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:03,007:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-14 14:13:03,007:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-14 14:13:03,187:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:03,188:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:03,190:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-12-14 14:13:03,383:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-14 14:13:03,446:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:03,446:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:03,626:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-14 14:13:03,784:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:03,785:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:03,785:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-12-14 14:13:04,164:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:04,165:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:04,424:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:04,424:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:04,456:INFO:Preparing preprocessing pipeline...
2023-12-14 14:13:04,456:INFO:Set up simple imputation.
2023-12-14 14:13:04,511:INFO:Set up encoding of ordinal features.
2023-12-14 14:13:04,612:INFO:Set up encoding of categorical features.
2023-12-14 14:13:04,612:INFO:Set up removing multicollinearity.
2023-12-14 14:13:04,612:INFO:Set up removing outliers.
2023-12-14 14:13:04,612:INFO:Set up imbalanced handling.
2023-12-14 14:13:04,612:INFO:Set up feature normalization.
2023-12-14 14:13:04,612:INFO:Set up column name cleaning.
2023-12-14 14:13:06,479:INFO:Finished creating preprocessing pipeline.
2023-12-14 14:13:07,575:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\talla\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(ex...
                                                                              sampling_strategy='auto')))),
                ('normalize',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=RobustScaler(copy=True,
                                                             quantile_range=(25.0,
                                                                             75.0),
                                                             unit_variance=False,
                                                             with_centering=True,
                                                             with_scaling=True))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-12-14 14:13:07,575:INFO:Creating final display dataframe.
2023-12-14 14:13:10,926:INFO:Setup _display_container:                     Description             Value
0                    Session id                42
1                        Target            target
2                   Target type            Binary
3           Original data shape       (33413, 20)
4        Transformed data shape       (32740, 20)
5   Transformed train set shape       (29398, 20)
6    Transformed test set shape        (3342, 20)
7              Ordinal features                19
8          Categorical features                19
9                    Preprocess              True
10              Imputation type            simple
11           Numeric imputation              mean
12       Categorical imputation              mode
13     Maximum one-hot encoding                25
14              Encoding method              None
15     Remove multicollinearity              True
16  Multicollinearity threshold               0.9
17              Remove outliers              True
18           Outliers threshold              0.05
19                Fix imbalance              True
20         Fix imbalance method             SMOTE
21                    Normalize              True
22             Normalize method            robust
23               Fold Generator   StratifiedKFold
24                  Fold Number                10
25                     CPU Jobs                -1
26                      Use GPU             False
27               Log Experiment             False
28              Experiment Name  clf-default-name
29                          USI              18bb
2023-12-14 14:13:11,143:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:11,143:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:11,243:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:11,243:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-14 14:13:11,256:INFO:setup() successfully completed in 9.38s...............
2023-12-14 14:13:20,409:INFO:Initializing compare_models()
2023-12-14 14:13:20,410:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, include=None, exclude=None, fold=5, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, 'include': None, 'exclude': None, 'fold': 5, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>})
2023-12-14 14:13:20,410:INFO:Checking exceptions
2023-12-14 14:13:20,435:INFO:Preparing display monitor
2023-12-14 14:13:20,491:INFO:Initializing Logistic Regression
2023-12-14 14:13:20,491:INFO:Total runtime is 0.0 minutes
2023-12-14 14:13:20,500:INFO:SubProcess create_model() called ==================================
2023-12-14 14:13:20,501:INFO:Initializing create_model()
2023-12-14 14:13:20,501:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:13:20,501:INFO:Checking exceptions
2023-12-14 14:13:20,501:INFO:Importing libraries
2023-12-14 14:13:20,502:INFO:Copying training dataset
2023-12-14 14:13:20,541:INFO:Defining folds
2023-12-14 14:13:20,541:INFO:Declaring metric variables
2023-12-14 14:13:20,554:INFO:Importing untrained model
2023-12-14 14:13:20,564:INFO:Logistic Regression Imported successfully
2023-12-14 14:13:20,581:INFO:Starting cross validation
2023-12-14 14:13:20,588:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:13:33,612:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:13:33,612:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:13:33,625:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:13:33,639:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:13:42,672:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:13:46,439:INFO:Calculating mean and std
2023-12-14 14:13:46,439:INFO:Creating metrics dataframe
2023-12-14 14:13:46,439:INFO:Uploading results into container
2023-12-14 14:13:46,439:INFO:Uploading model into container now
2023-12-14 14:13:46,439:INFO:_master_model_container: 1
2023-12-14 14:13:46,439:INFO:_display_container: 2
2023-12-14 14:13:46,439:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-12-14 14:13:46,439:INFO:create_model() successfully completed......................................
2023-12-14 14:13:46,626:INFO:SubProcess create_model() end ==================================
2023-12-14 14:13:46,626:INFO:Creating metrics dataframe
2023-12-14 14:13:46,639:INFO:Initializing K Neighbors Classifier
2023-12-14 14:13:46,639:INFO:Total runtime is 0.4357982794443766 minutes
2023-12-14 14:13:46,655:INFO:SubProcess create_model() called ==================================
2023-12-14 14:13:46,655:INFO:Initializing create_model()
2023-12-14 14:13:46,655:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:13:46,655:INFO:Checking exceptions
2023-12-14 14:13:46,655:INFO:Importing libraries
2023-12-14 14:13:46,655:INFO:Copying training dataset
2023-12-14 14:13:46,672:INFO:Defining folds
2023-12-14 14:13:46,672:INFO:Declaring metric variables
2023-12-14 14:13:46,672:INFO:Importing untrained model
2023-12-14 14:13:46,688:INFO:K Neighbors Classifier Imported successfully
2023-12-14 14:13:46,689:INFO:Starting cross validation
2023-12-14 14:13:46,689:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:13:48,509:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:13:48,523:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:13:48,526:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:13:48,539:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:02,147:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:07,930:INFO:Calculating mean and std
2023-12-14 14:14:07,931:INFO:Creating metrics dataframe
2023-12-14 14:14:07,935:INFO:Uploading results into container
2023-12-14 14:14:07,935:INFO:Uploading model into container now
2023-12-14 14:14:07,936:INFO:_master_model_container: 2
2023-12-14 14:14:07,936:INFO:_display_container: 2
2023-12-14 14:14:07,936:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-12-14 14:14:07,936:INFO:create_model() successfully completed......................................
2023-12-14 14:14:08,040:INFO:SubProcess create_model() end ==================================
2023-12-14 14:14:08,040:INFO:Creating metrics dataframe
2023-12-14 14:14:08,064:INFO:Initializing Naive Bayes
2023-12-14 14:14:08,072:INFO:Total runtime is 0.793012797832489 minutes
2023-12-14 14:14:08,078:INFO:SubProcess create_model() called ==================================
2023-12-14 14:14:08,078:INFO:Initializing create_model()
2023-12-14 14:14:08,078:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:14:08,078:INFO:Checking exceptions
2023-12-14 14:14:08,078:INFO:Importing libraries
2023-12-14 14:14:08,078:INFO:Copying training dataset
2023-12-14 14:14:08,117:INFO:Defining folds
2023-12-14 14:14:08,117:INFO:Declaring metric variables
2023-12-14 14:14:08,125:INFO:Importing untrained model
2023-12-14 14:14:08,129:INFO:Naive Bayes Imported successfully
2023-12-14 14:14:08,144:INFO:Starting cross validation
2023-12-14 14:14:08,144:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:14:09,924:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:09,944:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:09,944:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:10,007:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:17,743:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:20,978:INFO:Calculating mean and std
2023-12-14 14:14:20,978:INFO:Creating metrics dataframe
2023-12-14 14:14:20,989:INFO:Uploading results into container
2023-12-14 14:14:20,991:INFO:Uploading model into container now
2023-12-14 14:14:20,992:INFO:_master_model_container: 3
2023-12-14 14:14:20,992:INFO:_display_container: 2
2023-12-14 14:14:20,992:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-12-14 14:14:20,993:INFO:create_model() successfully completed......................................
2023-12-14 14:14:21,106:INFO:SubProcess create_model() end ==================================
2023-12-14 14:14:21,106:INFO:Creating metrics dataframe
2023-12-14 14:14:21,125:INFO:Initializing Decision Tree Classifier
2023-12-14 14:14:21,126:INFO:Total runtime is 1.0105684598286946 minutes
2023-12-14 14:14:21,132:INFO:SubProcess create_model() called ==================================
2023-12-14 14:14:21,133:INFO:Initializing create_model()
2023-12-14 14:14:21,133:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:14:21,134:INFO:Checking exceptions
2023-12-14 14:14:21,134:INFO:Importing libraries
2023-12-14 14:14:21,134:INFO:Copying training dataset
2023-12-14 14:14:21,172:INFO:Defining folds
2023-12-14 14:14:21,173:INFO:Declaring metric variables
2023-12-14 14:14:21,176:INFO:Importing untrained model
2023-12-14 14:14:21,193:INFO:Decision Tree Classifier Imported successfully
2023-12-14 14:14:21,214:INFO:Starting cross validation
2023-12-14 14:14:21,219:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:14:22,925:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:22,956:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:22,962:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:22,993:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:30,594:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:33,714:INFO:Calculating mean and std
2023-12-14 14:14:33,714:INFO:Creating metrics dataframe
2023-12-14 14:14:33,714:INFO:Uploading results into container
2023-12-14 14:14:33,714:INFO:Uploading model into container now
2023-12-14 14:14:33,714:INFO:_master_model_container: 4
2023-12-14 14:14:33,714:INFO:_display_container: 2
2023-12-14 14:14:33,714:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=42, splitter='best')
2023-12-14 14:14:33,714:INFO:create_model() successfully completed......................................
2023-12-14 14:14:33,838:INFO:SubProcess create_model() end ==================================
2023-12-14 14:14:33,838:INFO:Creating metrics dataframe
2023-12-14 14:14:33,863:INFO:Initializing SVM - Linear Kernel
2023-12-14 14:14:33,863:INFO:Total runtime is 1.2228639841079711 minutes
2023-12-14 14:14:33,866:INFO:SubProcess create_model() called ==================================
2023-12-14 14:14:33,866:INFO:Initializing create_model()
2023-12-14 14:14:33,866:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:14:33,866:INFO:Checking exceptions
2023-12-14 14:14:33,866:INFO:Importing libraries
2023-12-14 14:14:33,866:INFO:Copying training dataset
2023-12-14 14:14:33,908:INFO:Defining folds
2023-12-14 14:14:33,909:INFO:Declaring metric variables
2023-12-14 14:14:33,913:INFO:Importing untrained model
2023-12-14 14:14:33,928:INFO:SVM - Linear Kernel Imported successfully
2023-12-14 14:14:33,943:INFO:Starting cross validation
2023-12-14 14:14:33,946:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:14:35,599:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:35,610:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:35,627:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:35,640:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:42,506:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-14 14:14:42,507:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-14 14:14:42,507:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-14 14:14:42,523:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-14 14:14:43,441:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:46,639:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-14 14:14:46,655:INFO:Calculating mean and std
2023-12-14 14:14:46,657:INFO:Creating metrics dataframe
2023-12-14 14:14:46,665:INFO:Uploading results into container
2023-12-14 14:14:46,665:INFO:Uploading model into container now
2023-12-14 14:14:46,665:INFO:_master_model_container: 5
2023-12-14 14:14:46,665:INFO:_display_container: 2
2023-12-14 14:14:46,665:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-12-14 14:14:46,665:INFO:create_model() successfully completed......................................
2023-12-14 14:14:46,757:INFO:SubProcess create_model() end ==================================
2023-12-14 14:14:46,757:INFO:Creating metrics dataframe
2023-12-14 14:14:46,790:INFO:Initializing Ridge Classifier
2023-12-14 14:14:46,791:INFO:Total runtime is 1.4383266806602477 minutes
2023-12-14 14:14:46,793:INFO:SubProcess create_model() called ==================================
2023-12-14 14:14:46,793:INFO:Initializing create_model()
2023-12-14 14:14:46,793:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:14:46,793:INFO:Checking exceptions
2023-12-14 14:14:46,793:INFO:Importing libraries
2023-12-14 14:14:46,793:INFO:Copying training dataset
2023-12-14 14:14:46,830:INFO:Defining folds
2023-12-14 14:14:46,830:INFO:Declaring metric variables
2023-12-14 14:14:46,830:INFO:Importing untrained model
2023-12-14 14:14:46,846:INFO:Ridge Classifier Imported successfully
2023-12-14 14:14:46,861:INFO:Starting cross validation
2023-12-14 14:14:46,861:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:14:48,551:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:48,557:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:48,561:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:54,898:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-14 14:14:54,969:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-14 14:14:55,013:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-14 14:14:55,033:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-14 14:14:56,196:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:14:59,334:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-14 14:14:59,358:INFO:Calculating mean and std
2023-12-14 14:14:59,358:INFO:Creating metrics dataframe
2023-12-14 14:14:59,358:INFO:Uploading results into container
2023-12-14 14:14:59,358:INFO:Uploading model into container now
2023-12-14 14:14:59,358:INFO:_master_model_container: 6
2023-12-14 14:14:59,358:INFO:_display_container: 2
2023-12-14 14:14:59,358:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=42, solver='auto',
                tol=0.0001)
2023-12-14 14:14:59,358:INFO:create_model() successfully completed......................................
2023-12-14 14:14:59,458:INFO:SubProcess create_model() end ==================================
2023-12-14 14:14:59,458:INFO:Creating metrics dataframe
2023-12-14 14:14:59,474:INFO:Initializing Random Forest Classifier
2023-12-14 14:14:59,474:INFO:Total runtime is 1.6497234940528869 minutes
2023-12-14 14:14:59,494:INFO:SubProcess create_model() called ==================================
2023-12-14 14:14:59,496:INFO:Initializing create_model()
2023-12-14 14:14:59,496:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:14:59,496:INFO:Checking exceptions
2023-12-14 14:14:59,496:INFO:Importing libraries
2023-12-14 14:14:59,496:INFO:Copying training dataset
2023-12-14 14:14:59,534:INFO:Defining folds
2023-12-14 14:14:59,534:INFO:Declaring metric variables
2023-12-14 14:14:59,545:INFO:Importing untrained model
2023-12-14 14:14:59,548:INFO:Random Forest Classifier Imported successfully
2023-12-14 14:14:59,567:INFO:Starting cross validation
2023-12-14 14:14:59,575:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:15:01,352:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:01,367:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:01,427:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:01,475:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:12,809:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:17,042:INFO:Calculating mean and std
2023-12-14 14:15:17,043:INFO:Creating metrics dataframe
2023-12-14 14:15:17,043:INFO:Uploading results into container
2023-12-14 14:15:17,043:INFO:Uploading model into container now
2023-12-14 14:15:17,043:INFO:_master_model_container: 7
2023-12-14 14:15:17,043:INFO:_display_container: 2
2023-12-14 14:15:17,043:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2023-12-14 14:15:17,043:INFO:create_model() successfully completed......................................
2023-12-14 14:15:17,176:INFO:SubProcess create_model() end ==================================
2023-12-14 14:15:17,176:INFO:Creating metrics dataframe
2023-12-14 14:15:17,193:INFO:Initializing Quadratic Discriminant Analysis
2023-12-14 14:15:17,193:INFO:Total runtime is 1.9450246413548786 minutes
2023-12-14 14:15:17,208:INFO:SubProcess create_model() called ==================================
2023-12-14 14:15:17,208:INFO:Initializing create_model()
2023-12-14 14:15:17,208:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:15:17,208:INFO:Checking exceptions
2023-12-14 14:15:17,208:INFO:Importing libraries
2023-12-14 14:15:17,208:INFO:Copying training dataset
2023-12-14 14:15:17,247:INFO:Defining folds
2023-12-14 14:15:17,247:INFO:Declaring metric variables
2023-12-14 14:15:17,250:INFO:Importing untrained model
2023-12-14 14:15:17,264:INFO:Quadratic Discriminant Analysis Imported successfully
2023-12-14 14:15:17,279:INFO:Starting cross validation
2023-12-14 14:15:17,279:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:15:18,976:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:18,976:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:18,976:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:18,986:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:26,546:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:29,636:INFO:Calculating mean and std
2023-12-14 14:15:29,636:INFO:Creating metrics dataframe
2023-12-14 14:15:29,636:INFO:Uploading results into container
2023-12-14 14:15:29,641:INFO:Uploading model into container now
2023-12-14 14:15:29,641:INFO:_master_model_container: 8
2023-12-14 14:15:29,641:INFO:_display_container: 2
2023-12-14 14:15:29,644:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-12-14 14:15:29,644:INFO:create_model() successfully completed......................................
2023-12-14 14:15:29,746:INFO:SubProcess create_model() end ==================================
2023-12-14 14:15:29,746:INFO:Creating metrics dataframe
2023-12-14 14:15:29,762:INFO:Initializing Ada Boost Classifier
2023-12-14 14:15:29,762:INFO:Total runtime is 2.154512782891591 minutes
2023-12-14 14:15:29,762:INFO:SubProcess create_model() called ==================================
2023-12-14 14:15:29,762:INFO:Initializing create_model()
2023-12-14 14:15:29,762:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:15:29,762:INFO:Checking exceptions
2023-12-14 14:15:29,762:INFO:Importing libraries
2023-12-14 14:15:29,762:INFO:Copying training dataset
2023-12-14 14:15:29,803:INFO:Defining folds
2023-12-14 14:15:29,803:INFO:Declaring metric variables
2023-12-14 14:15:29,810:INFO:Importing untrained model
2023-12-14 14:15:29,822:INFO:Ada Boost Classifier Imported successfully
2023-12-14 14:15:29,826:INFO:Starting cross validation
2023-12-14 14:15:29,849:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:15:31,513:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:31,513:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:31,533:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:31,584:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:41,452:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:48,231:INFO:Calculating mean and std
2023-12-14 14:15:48,231:INFO:Creating metrics dataframe
2023-12-14 14:15:48,231:INFO:Uploading results into container
2023-12-14 14:15:48,231:INFO:Uploading model into container now
2023-12-14 14:15:48,231:INFO:_master_model_container: 9
2023-12-14 14:15:48,231:INFO:_display_container: 2
2023-12-14 14:15:48,243:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=42)
2023-12-14 14:15:48,243:INFO:create_model() successfully completed......................................
2023-12-14 14:15:48,410:INFO:SubProcess create_model() end ==================================
2023-12-14 14:15:48,410:INFO:Creating metrics dataframe
2023-12-14 14:15:48,442:INFO:Initializing Gradient Boosting Classifier
2023-12-14 14:15:48,442:INFO:Total runtime is 2.465843534469604 minutes
2023-12-14 14:15:48,442:INFO:SubProcess create_model() called ==================================
2023-12-14 14:15:48,442:INFO:Initializing create_model()
2023-12-14 14:15:48,442:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:15:48,442:INFO:Checking exceptions
2023-12-14 14:15:48,442:INFO:Importing libraries
2023-12-14 14:15:48,442:INFO:Copying training dataset
2023-12-14 14:15:48,513:INFO:Defining folds
2023-12-14 14:15:48,513:INFO:Declaring metric variables
2023-12-14 14:15:48,530:INFO:Importing untrained model
2023-12-14 14:15:48,533:INFO:Gradient Boosting Classifier Imported successfully
2023-12-14 14:15:48,567:INFO:Starting cross validation
2023-12-14 14:15:48,576:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:15:50,344:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:50,397:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:50,414:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:15:50,475:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:02,146:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:10,935:INFO:Calculating mean and std
2023-12-14 14:16:10,935:INFO:Creating metrics dataframe
2023-12-14 14:16:10,935:INFO:Uploading results into container
2023-12-14 14:16:10,935:INFO:Uploading model into container now
2023-12-14 14:16:10,935:INFO:_master_model_container: 10
2023-12-14 14:16:10,935:INFO:_display_container: 2
2023-12-14 14:16:10,935:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-14 14:16:10,935:INFO:create_model() successfully completed......................................
2023-12-14 14:16:11,114:INFO:SubProcess create_model() end ==================================
2023-12-14 14:16:11,116:INFO:Creating metrics dataframe
2023-12-14 14:16:11,151:INFO:Initializing Linear Discriminant Analysis
2023-12-14 14:16:11,151:INFO:Total runtime is 2.844324417908986 minutes
2023-12-14 14:16:11,160:INFO:SubProcess create_model() called ==================================
2023-12-14 14:16:11,160:INFO:Initializing create_model()
2023-12-14 14:16:11,160:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:16:11,160:INFO:Checking exceptions
2023-12-14 14:16:11,160:INFO:Importing libraries
2023-12-14 14:16:11,160:INFO:Copying training dataset
2023-12-14 14:16:11,214:INFO:Defining folds
2023-12-14 14:16:11,214:INFO:Declaring metric variables
2023-12-14 14:16:11,214:INFO:Importing untrained model
2023-12-14 14:16:11,232:INFO:Linear Discriminant Analysis Imported successfully
2023-12-14 14:16:11,257:INFO:Starting cross validation
2023-12-14 14:16:11,260:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:16:13,245:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:13,275:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:13,280:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:13,355:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:21,545:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:27,595:INFO:Calculating mean and std
2023-12-14 14:16:27,599:INFO:Creating metrics dataframe
2023-12-14 14:16:27,607:INFO:Uploading results into container
2023-12-14 14:16:27,612:INFO:Uploading model into container now
2023-12-14 14:16:27,612:INFO:_master_model_container: 11
2023-12-14 14:16:27,613:INFO:_display_container: 2
2023-12-14 14:16:27,613:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-12-14 14:16:27,614:INFO:create_model() successfully completed......................................
2023-12-14 14:16:27,798:INFO:SubProcess create_model() end ==================================
2023-12-14 14:16:27,799:INFO:Creating metrics dataframe
2023-12-14 14:16:27,831:INFO:Initializing Extra Trees Classifier
2023-12-14 14:16:27,831:INFO:Total runtime is 3.122340635458628 minutes
2023-12-14 14:16:27,847:INFO:SubProcess create_model() called ==================================
2023-12-14 14:16:27,847:INFO:Initializing create_model()
2023-12-14 14:16:27,847:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:16:27,847:INFO:Checking exceptions
2023-12-14 14:16:27,847:INFO:Importing libraries
2023-12-14 14:16:27,847:INFO:Copying training dataset
2023-12-14 14:16:27,930:INFO:Defining folds
2023-12-14 14:16:27,930:INFO:Declaring metric variables
2023-12-14 14:16:27,937:INFO:Importing untrained model
2023-12-14 14:16:27,944:INFO:Extra Trees Classifier Imported successfully
2023-12-14 14:16:27,944:INFO:Starting cross validation
2023-12-14 14:16:27,960:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:16:29,747:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:29,766:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:29,779:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:29,810:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:42,179:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:49,513:INFO:Calculating mean and std
2023-12-14 14:16:49,515:INFO:Creating metrics dataframe
2023-12-14 14:16:49,529:INFO:Uploading results into container
2023-12-14 14:16:49,530:INFO:Uploading model into container now
2023-12-14 14:16:49,532:INFO:_master_model_container: 12
2023-12-14 14:16:49,532:INFO:_display_container: 2
2023-12-14 14:16:49,532:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False)
2023-12-14 14:16:49,532:INFO:create_model() successfully completed......................................
2023-12-14 14:16:49,698:INFO:SubProcess create_model() end ==================================
2023-12-14 14:16:49,698:INFO:Creating metrics dataframe
2023-12-14 14:16:49,729:INFO:Initializing Light Gradient Boosting Machine
2023-12-14 14:16:49,729:INFO:Total runtime is 3.4873062769571934 minutes
2023-12-14 14:16:49,729:INFO:SubProcess create_model() called ==================================
2023-12-14 14:16:49,729:INFO:Initializing create_model()
2023-12-14 14:16:49,729:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:16:49,729:INFO:Checking exceptions
2023-12-14 14:16:49,729:INFO:Importing libraries
2023-12-14 14:16:49,729:INFO:Copying training dataset
2023-12-14 14:16:49,798:INFO:Defining folds
2023-12-14 14:16:49,804:INFO:Declaring metric variables
2023-12-14 14:16:49,829:INFO:Importing untrained model
2023-12-14 14:16:49,839:INFO:Light Gradient Boosting Machine Imported successfully
2023-12-14 14:16:49,844:INFO:Starting cross validation
2023-12-14 14:16:49,862:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:16:52,164:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:52,181:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:52,201:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:16:52,216:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:17:01,882:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:17:06,899:INFO:Calculating mean and std
2023-12-14 14:17:06,899:INFO:Creating metrics dataframe
2023-12-14 14:17:06,899:INFO:Uploading results into container
2023-12-14 14:17:06,899:INFO:Uploading model into container now
2023-12-14 14:17:06,912:INFO:_master_model_container: 13
2023-12-14 14:17:06,912:INFO:_display_container: 2
2023-12-14 14:17:06,913:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-12-14 14:17:06,914:INFO:create_model() successfully completed......................................
2023-12-14 14:17:07,047:INFO:SubProcess create_model() end ==================================
2023-12-14 14:17:07,047:INFO:Creating metrics dataframe
2023-12-14 14:17:07,081:INFO:Initializing Dummy Classifier
2023-12-14 14:17:07,081:INFO:Total runtime is 3.776504270235697 minutes
2023-12-14 14:17:07,081:INFO:SubProcess create_model() called ==================================
2023-12-14 14:17:07,081:INFO:Initializing create_model()
2023-12-14 14:17:07,081:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=dummy, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A4381C90>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:17:07,081:INFO:Checking exceptions
2023-12-14 14:17:07,097:INFO:Importing libraries
2023-12-14 14:17:07,097:INFO:Copying training dataset
2023-12-14 14:17:07,146:INFO:Defining folds
2023-12-14 14:17:07,146:INFO:Declaring metric variables
2023-12-14 14:17:07,156:INFO:Importing untrained model
2023-12-14 14:17:07,179:INFO:Dummy Classifier Imported successfully
2023-12-14 14:17:07,199:INFO:Starting cross validation
2023-12-14 14:17:07,205:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:17:09,284:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:17:09,284:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:17:09,295:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:17:09,305:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:17:15,466:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-14 14:17:15,484:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-14 14:17:15,486:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-14 14:17:17,466:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:17:22,186:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-12-14 14:17:22,218:INFO:Calculating mean and std
2023-12-14 14:17:22,218:INFO:Creating metrics dataframe
2023-12-14 14:17:22,231:INFO:Uploading results into container
2023-12-14 14:17:22,233:INFO:Uploading model into container now
2023-12-14 14:17:22,234:INFO:_master_model_container: 14
2023-12-14 14:17:22,234:INFO:_display_container: 2
2023-12-14 14:17:22,234:INFO:DummyClassifier(constant=None, random_state=42, strategy='prior')
2023-12-14 14:17:22,234:INFO:create_model() successfully completed......................................
2023-12-14 14:17:22,429:INFO:SubProcess create_model() end ==================================
2023-12-14 14:17:22,429:INFO:Creating metrics dataframe
2023-12-14 14:17:22,501:INFO:Initializing create_model()
2023-12-14 14:17:22,501:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:17:22,501:INFO:Checking exceptions
2023-12-14 14:17:22,514:INFO:Importing libraries
2023-12-14 14:17:22,514:INFO:Copying training dataset
2023-12-14 14:17:22,579:INFO:Defining folds
2023-12-14 14:17:22,579:INFO:Declaring metric variables
2023-12-14 14:17:22,579:INFO:Importing untrained model
2023-12-14 14:17:22,579:INFO:Declaring custom model
2023-12-14 14:17:22,579:INFO:Gradient Boosting Classifier Imported successfully
2023-12-14 14:17:22,579:INFO:Cross validation set to False
2023-12-14 14:17:22,579:INFO:Fitting Model
2023-12-14 14:17:29,994:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-14 14:17:29,994:INFO:create_model() successfully completed......................................
2023-12-14 14:17:30,175:INFO:_master_model_container: 14
2023-12-14 14:17:30,175:INFO:_display_container: 2
2023-12-14 14:17:30,176:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-14 14:17:30,177:INFO:compare_models() successfully completed......................................
2023-12-14 14:18:20,770:INFO:Initializing create_model()
2023-12-14 14:18:20,770:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=gbc, fold=5, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:18:20,770:INFO:Checking exceptions
2023-12-14 14:18:20,809:INFO:Importing libraries
2023-12-14 14:18:20,810:INFO:Copying training dataset
2023-12-14 14:18:20,856:INFO:Defining folds
2023-12-14 14:18:20,857:INFO:Declaring metric variables
2023-12-14 14:18:20,863:INFO:Importing untrained model
2023-12-14 14:18:20,876:INFO:Gradient Boosting Classifier Imported successfully
2023-12-14 14:18:20,898:INFO:Starting cross validation
2023-12-14 14:18:20,903:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:18:24,184:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:18:24,203:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:18:24,316:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:18:24,488:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:18:40,568:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:18:48,161:INFO:Calculating mean and std
2023-12-14 14:18:48,161:INFO:Creating metrics dataframe
2023-12-14 14:18:48,171:INFO:Finalizing model
2023-12-14 14:18:55,601:INFO:Uploading results into container
2023-12-14 14:18:55,601:INFO:Uploading model into container now
2023-12-14 14:18:55,615:INFO:_master_model_container: 15
2023-12-14 14:18:55,615:INFO:_display_container: 3
2023-12-14 14:18:55,615:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-14 14:18:55,615:INFO:create_model() successfully completed......................................
2023-12-14 14:19:14,978:INFO:Initializing tune_model()
2023-12-14 14:19:14,978:INFO:tune_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=10, round=10, n_iter=10, custom_grid=None, optimize=AUC, custom_scorer=None, search_library=optuna, search_algorithm=tpe, early_stopping=False, early_stopping_max_iters=10, choose_better=True, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, return_train_score=False, kwargs={})
2023-12-14 14:19:14,978:INFO:Checking exceptions
2023-12-14 14:19:14,979:INFO:Soft dependency imported: optuna: 3.5.0
2023-12-14 14:19:28,995:INFO:Copying training dataset
2023-12-14 14:19:29,025:INFO:Checking base model
2023-12-14 14:19:29,025:INFO:Base model : Gradient Boosting Classifier
2023-12-14 14:19:29,037:INFO:Declaring metric variables
2023-12-14 14:19:29,053:INFO:Defining Hyperparameters
2023-12-14 14:19:29,387:INFO:Tuning with n_jobs=-1
2023-12-14 14:19:29,387:INFO:Initializing optuna.integration.OptunaSearchCV
2023-12-14 14:30:33,270:INFO:best_params: {'actual_estimator__n_estimators': 36, 'actual_estimator__learning_rate': 0.0011667201608402194, 'actual_estimator__subsample': 0.40727313000398024, 'actual_estimator__min_samples_split': 8, 'actual_estimator__min_samples_leaf': 3, 'actual_estimator__max_depth': 9, 'actual_estimator__min_impurity_decrease': 0.4107423397873473, 'actual_estimator__max_features': 0.59426897669419}
2023-12-14 14:30:33,270:INFO:Hyperparameter search completed
2023-12-14 14:30:33,270:INFO:SubProcess create_model() called ==================================
2023-12-14 14:30:33,270:INFO:Initializing create_model()
2023-12-14 14:30:33,270:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=10, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000166A01E3DD0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={'n_estimators': 36, 'learning_rate': 0.0011667201608402194, 'subsample': 0.40727313000398024, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_depth': 9, 'min_impurity_decrease': 0.4107423397873473, 'max_features': 0.59426897669419})
2023-12-14 14:30:33,270:INFO:Checking exceptions
2023-12-14 14:30:33,270:INFO:Importing libraries
2023-12-14 14:30:33,270:INFO:Copying training dataset
2023-12-14 14:30:33,341:INFO:Defining folds
2023-12-14 14:30:33,341:INFO:Declaring metric variables
2023-12-14 14:30:33,354:INFO:Importing untrained model
2023-12-14 14:30:33,354:INFO:Declaring custom model
2023-12-14 14:30:33,357:INFO:Gradient Boosting Classifier Imported successfully
2023-12-14 14:30:33,387:INFO:Starting cross validation
2023-12-14 14:30:33,405:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:31:19,591:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:31:19,597:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:31:19,619:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:31:47,258:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:31:47,375:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:31:47,555:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:31:47,565:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:03,890:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:04,027:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:13,361:INFO:Calculating mean and std
2023-12-14 14:32:13,361:INFO:Creating metrics dataframe
2023-12-14 14:32:13,361:INFO:Finalizing model
2023-12-14 14:32:20,967:INFO:Uploading results into container
2023-12-14 14:32:20,967:INFO:Uploading model into container now
2023-12-14 14:32:20,967:INFO:_master_model_container: 16
2023-12-14 14:32:20,967:INFO:_display_container: 4
2023-12-14 14:32:20,972:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.0011667201608402194, loss='log_loss',
                           max_depth=9, max_features=0.59426897669419,
                           max_leaf_nodes=None,
                           min_impurity_decrease=0.4107423397873473,
                           min_samples_leaf=3, min_samples_split=8,
                           min_weight_fraction_leaf=0.0, n_estimators=36,
                           n_iter_no_change=None, random_state=42,
                           subsample=0.40727313000398024, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-14 14:32:20,972:INFO:create_model() successfully completed......................................
2023-12-14 14:32:21,177:INFO:SubProcess create_model() end ==================================
2023-12-14 14:32:21,177:INFO:choose_better activated
2023-12-14 14:32:21,177:INFO:SubProcess create_model() called ==================================
2023-12-14 14:32:21,193:INFO:Initializing create_model()
2023-12-14 14:32:21,193:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x00000166A4E95A90>, estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-14 14:32:21,193:INFO:Checking exceptions
2023-12-14 14:32:21,193:INFO:Importing libraries
2023-12-14 14:32:21,193:INFO:Copying training dataset
2023-12-14 14:32:21,256:INFO:Defining folds
2023-12-14 14:32:21,256:INFO:Declaring metric variables
2023-12-14 14:32:21,257:INFO:Importing untrained model
2023-12-14 14:32:21,257:INFO:Declaring custom model
2023-12-14 14:32:21,259:INFO:Gradient Boosting Classifier Imported successfully
2023-12-14 14:32:21,260:INFO:Starting cross validation
2023-12-14 14:32:21,265:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-14 14:32:23,193:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:23,199:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:23,199:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:23,225:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:35,163:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:35,191:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:35,283:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:35,407:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:47,618:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:47,691:WARNING:C:\Users\talla\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

2023-12-14 14:32:58,033:INFO:Calculating mean and std
2023-12-14 14:32:58,033:INFO:Creating metrics dataframe
2023-12-14 14:32:58,033:INFO:Finalizing model
2023-12-14 14:33:06,578:INFO:Uploading results into container
2023-12-14 14:33:06,578:INFO:Uploading model into container now
2023-12-14 14:33:06,593:INFO:_master_model_container: 17
2023-12-14 14:33:06,593:INFO:_display_container: 5
2023-12-14 14:33:06,593:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-14 14:33:06,593:INFO:create_model() successfully completed......................................
2023-12-14 14:33:06,744:INFO:SubProcess create_model() end ==================================
2023-12-14 14:33:06,744:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False) result for AUC is 0.7507
2023-12-14 14:33:06,744:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.0011667201608402194, loss='log_loss',
                           max_depth=9, max_features=0.59426897669419,
                           max_leaf_nodes=None,
                           min_impurity_decrease=0.4107423397873473,
                           min_samples_leaf=3, min_samples_split=8,
                           min_weight_fraction_leaf=0.0, n_estimators=36,
                           n_iter_no_change=None, random_state=42,
                           subsample=0.40727313000398024, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False) result for AUC is 0.7517777582
2023-12-14 14:33:06,744:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.0011667201608402194, loss='log_loss',
                           max_depth=9, max_features=0.59426897669419,
                           max_leaf_nodes=None,
                           min_impurity_decrease=0.4107423397873473,
                           min_samples_leaf=3, min_samples_split=8,
                           min_weight_fraction_leaf=0.0, n_estimators=36,
                           n_iter_no_change=None, random_state=42,
                           subsample=0.40727313000398024, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False) is best model
2023-12-14 14:33:06,744:INFO:choose_better completed
2023-12-14 14:33:06,776:INFO:_master_model_container: 17
2023-12-14 14:33:06,776:INFO:_display_container: 4
2023-12-14 14:33:06,776:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.0011667201608402194, loss='log_loss',
                           max_depth=9, max_features=0.59426897669419,
                           max_leaf_nodes=None,
                           min_impurity_decrease=0.4107423397873473,
                           min_samples_leaf=3, min_samples_split=8,
                           min_weight_fraction_leaf=0.0, n_estimators=36,
                           n_iter_no_change=None, random_state=42,
                           subsample=0.40727313000398024, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-14 14:33:06,776:INFO:tune_model() successfully completed......................................
